### ISSUE TITLE
Client Secret in Authenticator for backwards compatability

### ISSUE THREAD

**Issue by fxFlocke** [10Duke/10duke-web-client-pkce#2]
We have a Situation where we need to keep the ClientSecret in the Client, to be backwards compatible, since we moved to the PKCE-Flow.
Now in the new 10Duke Version, if your client has a secret, it's necessary to provide it in the PKCE-Flow.
The Authenticator does not have an option to pass it.

Please add this!

Thanks in advance, FtheDev!

**Comment by Jarkko-10Duke** [comment]
Version that allows specifying `client_secret` has now been released:

https://github.com/10Duke/10duke-web-client-pkce/releases/tag/v1.3.0
